// Generated by gencpp from file lslidar_ls_driver/angle_distortion_correctionRequest.msg
// DO NOT EDIT!


#ifndef LSLIDAR_LS_DRIVER_MESSAGE_ANGLE_DISTORTION_CORRECTIONREQUEST_H
#define LSLIDAR_LS_DRIVER_MESSAGE_ANGLE_DISTORTION_CORRECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_ls_driver
{
template <class ContainerAllocator>
struct angle_distortion_correctionRequest_
{
  typedef angle_distortion_correctionRequest_<ContainerAllocator> Type;

  angle_distortion_correctionRequest_()
    : angle_distortion_correction(0)  {
    }
  angle_distortion_correctionRequest_(const ContainerAllocator& _alloc)
    : angle_distortion_correction(0)  {
  (void)_alloc;
    }



   typedef int8_t _angle_distortion_correction_type;
  _angle_distortion_correction_type angle_distortion_correction;





  typedef boost::shared_ptr< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct angle_distortion_correctionRequest_

typedef ::lslidar_ls_driver::angle_distortion_correctionRequest_<std::allocator<void> > angle_distortion_correctionRequest;

typedef boost::shared_ptr< ::lslidar_ls_driver::angle_distortion_correctionRequest > angle_distortion_correctionRequestPtr;
typedef boost::shared_ptr< ::lslidar_ls_driver::angle_distortion_correctionRequest const> angle_distortion_correctionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle_distortion_correction == rhs.angle_distortion_correction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_ls_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24be7ab9b990f7316f28bc9cd35f82f4";
  }

  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24be7ab9b990f731ULL;
  static const uint64_t static_value2 = 0x6f28bc9cd35f82f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_ls_driver/angle_distortion_correctionRequest";
  }

  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 angle_distortion_correction\n"
;
  }

  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_distortion_correction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angle_distortion_correctionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_ls_driver::angle_distortion_correctionRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle_distortion_correction: ";
    Printer<int8_t>::stream(s, indent + "  ", v.angle_distortion_correction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_LS_DRIVER_MESSAGE_ANGLE_DISTORTION_CORRECTIONREQUEST_H
