// Generated by gencpp from file lslidar_ls_driver/angle_distortion_correctionResponse.msg
// DO NOT EDIT!


#ifndef LSLIDAR_LS_DRIVER_MESSAGE_ANGLE_DISTORTION_CORRECTIONRESPONSE_H
#define LSLIDAR_LS_DRIVER_MESSAGE_ANGLE_DISTORTION_CORRECTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_ls_driver
{
template <class ContainerAllocator>
struct angle_distortion_correctionResponse_
{
  typedef angle_distortion_correctionResponse_<ContainerAllocator> Type;

  angle_distortion_correctionResponse_()
    : result(false)  {
    }
  angle_distortion_correctionResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct angle_distortion_correctionResponse_

typedef ::lslidar_ls_driver::angle_distortion_correctionResponse_<std::allocator<void> > angle_distortion_correctionResponse;

typedef boost::shared_ptr< ::lslidar_ls_driver::angle_distortion_correctionResponse > angle_distortion_correctionResponsePtr;
typedef boost::shared_ptr< ::lslidar_ls_driver::angle_distortion_correctionResponse const> angle_distortion_correctionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_ls_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_ls_driver/angle_distortion_correctionResponse";
  }

  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"\n"
;
  }

  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angle_distortion_correctionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_ls_driver::angle_distortion_correctionResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_LS_DRIVER_MESSAGE_ANGLE_DISTORTION_CORRECTIONRESPONSE_H
