// Generated by gencpp from file lslidar_ls_driver/angle_distortion_correction.msg
// DO NOT EDIT!


#ifndef LSLIDAR_LS_DRIVER_MESSAGE_ANGLE_DISTORTION_CORRECTION_H
#define LSLIDAR_LS_DRIVER_MESSAGE_ANGLE_DISTORTION_CORRECTION_H

#include <ros/service_traits.h>


#include <lslidar_ls_driver/angle_distortion_correctionRequest.h>
#include <lslidar_ls_driver/angle_distortion_correctionResponse.h>


namespace lslidar_ls_driver
{

struct angle_distortion_correction
{

typedef angle_distortion_correctionRequest Request;
typedef angle_distortion_correctionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct angle_distortion_correction
} // namespace lslidar_ls_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lslidar_ls_driver::angle_distortion_correction > {
  static const char* value()
  {
    return "d983ffb854a179224eceb9c4385f0696";
  }

  static const char* value(const ::lslidar_ls_driver::angle_distortion_correction&) { return value(); }
};

template<>
struct DataType< ::lslidar_ls_driver::angle_distortion_correction > {
  static const char* value()
  {
    return "lslidar_ls_driver/angle_distortion_correction";
  }

  static const char* value(const ::lslidar_ls_driver::angle_distortion_correction&) { return value(); }
};


// service_traits::MD5Sum< ::lslidar_ls_driver::angle_distortion_correctionRequest> should match
// service_traits::MD5Sum< ::lslidar_ls_driver::angle_distortion_correction >
template<>
struct MD5Sum< ::lslidar_ls_driver::angle_distortion_correctionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_ls_driver::angle_distortion_correction >::value();
  }
  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_ls_driver::angle_distortion_correctionRequest> should match
// service_traits::DataType< ::lslidar_ls_driver::angle_distortion_correction >
template<>
struct DataType< ::lslidar_ls_driver::angle_distortion_correctionRequest>
{
  static const char* value()
  {
    return DataType< ::lslidar_ls_driver::angle_distortion_correction >::value();
  }
  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lslidar_ls_driver::angle_distortion_correctionResponse> should match
// service_traits::MD5Sum< ::lslidar_ls_driver::angle_distortion_correction >
template<>
struct MD5Sum< ::lslidar_ls_driver::angle_distortion_correctionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_ls_driver::angle_distortion_correction >::value();
  }
  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_ls_driver::angle_distortion_correctionResponse> should match
// service_traits::DataType< ::lslidar_ls_driver::angle_distortion_correction >
template<>
struct DataType< ::lslidar_ls_driver::angle_distortion_correctionResponse>
{
  static const char* value()
  {
    return DataType< ::lslidar_ls_driver::angle_distortion_correction >::value();
  }
  static const char* value(const ::lslidar_ls_driver::angle_distortion_correctionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LSLIDAR_LS_DRIVER_MESSAGE_ANGLE_DISTORTION_CORRECTION_H
