// Generated by gencpp from file lslidar_ls_driver/frame_rate.msg
// DO NOT EDIT!


#ifndef LSLIDAR_LS_DRIVER_MESSAGE_FRAME_RATE_H
#define LSLIDAR_LS_DRIVER_MESSAGE_FRAME_RATE_H

#include <ros/service_traits.h>


#include <lslidar_ls_driver/frame_rateRequest.h>
#include <lslidar_ls_driver/frame_rateResponse.h>


namespace lslidar_ls_driver
{

struct frame_rate
{

typedef frame_rateRequest Request;
typedef frame_rateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct frame_rate
} // namespace lslidar_ls_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lslidar_ls_driver::frame_rate > {
  static const char* value()
  {
    return "82b83e3f6f39bd297516edd9c8b8083a";
  }

  static const char* value(const ::lslidar_ls_driver::frame_rate&) { return value(); }
};

template<>
struct DataType< ::lslidar_ls_driver::frame_rate > {
  static const char* value()
  {
    return "lslidar_ls_driver/frame_rate";
  }

  static const char* value(const ::lslidar_ls_driver::frame_rate&) { return value(); }
};


// service_traits::MD5Sum< ::lslidar_ls_driver::frame_rateRequest> should match
// service_traits::MD5Sum< ::lslidar_ls_driver::frame_rate >
template<>
struct MD5Sum< ::lslidar_ls_driver::frame_rateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_ls_driver::frame_rate >::value();
  }
  static const char* value(const ::lslidar_ls_driver::frame_rateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_ls_driver::frame_rateRequest> should match
// service_traits::DataType< ::lslidar_ls_driver::frame_rate >
template<>
struct DataType< ::lslidar_ls_driver::frame_rateRequest>
{
  static const char* value()
  {
    return DataType< ::lslidar_ls_driver::frame_rate >::value();
  }
  static const char* value(const ::lslidar_ls_driver::frame_rateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lslidar_ls_driver::frame_rateResponse> should match
// service_traits::MD5Sum< ::lslidar_ls_driver::frame_rate >
template<>
struct MD5Sum< ::lslidar_ls_driver::frame_rateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_ls_driver::frame_rate >::value();
  }
  static const char* value(const ::lslidar_ls_driver::frame_rateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_ls_driver::frame_rateResponse> should match
// service_traits::DataType< ::lslidar_ls_driver::frame_rate >
template<>
struct DataType< ::lslidar_ls_driver::frame_rateResponse>
{
  static const char* value()
  {
    return DataType< ::lslidar_ls_driver::frame_rate >::value();
  }
  static const char* value(const ::lslidar_ls_driver::frame_rateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LSLIDAR_LS_DRIVER_MESSAGE_FRAME_RATE_H
