// Generated by gencpp from file lslidar_ls_driver/frame_rateRequest.msg
// DO NOT EDIT!


#ifndef LSLIDAR_LS_DRIVER_MESSAGE_FRAME_RATEREQUEST_H
#define LSLIDAR_LS_DRIVER_MESSAGE_FRAME_RATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_ls_driver
{
template <class ContainerAllocator>
struct frame_rateRequest_
{
  typedef frame_rateRequest_<ContainerAllocator> Type;

  frame_rateRequest_()
    : frame_rate(0)  {
    }
  frame_rateRequest_(const ContainerAllocator& _alloc)
    : frame_rate(0)  {
  (void)_alloc;
    }



   typedef int32_t _frame_rate_type;
  _frame_rate_type frame_rate;





  typedef boost::shared_ptr< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct frame_rateRequest_

typedef ::lslidar_ls_driver::frame_rateRequest_<std::allocator<void> > frame_rateRequest;

typedef boost::shared_ptr< ::lslidar_ls_driver::frame_rateRequest > frame_rateRequestPtr;
typedef boost::shared_ptr< ::lslidar_ls_driver::frame_rateRequest const> frame_rateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.frame_rate == rhs.frame_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_ls_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30e64d124f7d123c35b09bb3ee7f7eaf";
  }

  static const char* value(const ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30e64d124f7d123cULL;
  static const uint64_t static_value2 = 0x35b09bb3ee7f7eafULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_ls_driver/frame_rateRequest";
  }

  static const char* value(const ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 frame_rate\n"
;
  }

  static const char* value(const ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct frame_rateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_ls_driver::frame_rateRequest_<ContainerAllocator>& v)
  {
    s << indent << "frame_rate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frame_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_LS_DRIVER_MESSAGE_FRAME_RATEREQUEST_H
