// Generated by gencpp from file lslidar_ls_driver/invalid_data.msg
// DO NOT EDIT!


#ifndef LSLIDAR_LS_DRIVER_MESSAGE_INVALID_DATA_H
#define LSLIDAR_LS_DRIVER_MESSAGE_INVALID_DATA_H

#include <ros/service_traits.h>


#include <lslidar_ls_driver/invalid_dataRequest.h>
#include <lslidar_ls_driver/invalid_dataResponse.h>


namespace lslidar_ls_driver
{

struct invalid_data
{

typedef invalid_dataRequest Request;
typedef invalid_dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct invalid_data
} // namespace lslidar_ls_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lslidar_ls_driver::invalid_data > {
  static const char* value()
  {
    return "97f23ad7e27228b8c5d15cd432f4a379";
  }

  static const char* value(const ::lslidar_ls_driver::invalid_data&) { return value(); }
};

template<>
struct DataType< ::lslidar_ls_driver::invalid_data > {
  static const char* value()
  {
    return "lslidar_ls_driver/invalid_data";
  }

  static const char* value(const ::lslidar_ls_driver::invalid_data&) { return value(); }
};


// service_traits::MD5Sum< ::lslidar_ls_driver::invalid_dataRequest> should match
// service_traits::MD5Sum< ::lslidar_ls_driver::invalid_data >
template<>
struct MD5Sum< ::lslidar_ls_driver::invalid_dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_ls_driver::invalid_data >::value();
  }
  static const char* value(const ::lslidar_ls_driver::invalid_dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_ls_driver::invalid_dataRequest> should match
// service_traits::DataType< ::lslidar_ls_driver::invalid_data >
template<>
struct DataType< ::lslidar_ls_driver::invalid_dataRequest>
{
  static const char* value()
  {
    return DataType< ::lslidar_ls_driver::invalid_data >::value();
  }
  static const char* value(const ::lslidar_ls_driver::invalid_dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lslidar_ls_driver::invalid_dataResponse> should match
// service_traits::MD5Sum< ::lslidar_ls_driver::invalid_data >
template<>
struct MD5Sum< ::lslidar_ls_driver::invalid_dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_ls_driver::invalid_data >::value();
  }
  static const char* value(const ::lslidar_ls_driver::invalid_dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_ls_driver::invalid_dataResponse> should match
// service_traits::DataType< ::lslidar_ls_driver::invalid_data >
template<>
struct DataType< ::lslidar_ls_driver::invalid_dataResponse>
{
  static const char* value()
  {
    return DataType< ::lslidar_ls_driver::invalid_data >::value();
  }
  static const char* value(const ::lslidar_ls_driver::invalid_dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LSLIDAR_LS_DRIVER_MESSAGE_INVALID_DATA_H
