// Generated by gencpp from file lslidar_ls_driver/invalid_dataRequest.msg
// DO NOT EDIT!


#ifndef LSLIDAR_LS_DRIVER_MESSAGE_INVALID_DATAREQUEST_H
#define LSLIDAR_LS_DRIVER_MESSAGE_INVALID_DATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_ls_driver
{
template <class ContainerAllocator>
struct invalid_dataRequest_
{
  typedef invalid_dataRequest_<ContainerAllocator> Type;

  invalid_dataRequest_()
    : invalid_data(0)  {
    }
  invalid_dataRequest_(const ContainerAllocator& _alloc)
    : invalid_data(0)  {
  (void)_alloc;
    }



   typedef int32_t _invalid_data_type;
  _invalid_data_type invalid_data;





  typedef boost::shared_ptr< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct invalid_dataRequest_

typedef ::lslidar_ls_driver::invalid_dataRequest_<std::allocator<void> > invalid_dataRequest;

typedef boost::shared_ptr< ::lslidar_ls_driver::invalid_dataRequest > invalid_dataRequestPtr;
typedef boost::shared_ptr< ::lslidar_ls_driver::invalid_dataRequest const> invalid_dataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.invalid_data == rhs.invalid_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_ls_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a405c4044adc7385617ed79e4984b74";
  }

  static const char* value(const ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a405c4044adc738ULL;
  static const uint64_t static_value2 = 0x5617ed79e4984b74ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_ls_driver/invalid_dataRequest";
  }

  static const char* value(const ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 invalid_data\n"
;
  }

  static const char* value(const ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.invalid_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct invalid_dataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_ls_driver::invalid_dataRequest_<ContainerAllocator>& v)
  {
    s << indent << "invalid_data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.invalid_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_LS_DRIVER_MESSAGE_INVALID_DATAREQUEST_H
