// Generated by gencpp from file lslidar_ls_driver/standby_modeRequest.msg
// DO NOT EDIT!


#ifndef LSLIDAR_LS_DRIVER_MESSAGE_STANDBY_MODEREQUEST_H
#define LSLIDAR_LS_DRIVER_MESSAGE_STANDBY_MODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_ls_driver
{
template <class ContainerAllocator>
struct standby_modeRequest_
{
  typedef standby_modeRequest_<ContainerAllocator> Type;

  standby_modeRequest_()
    : standby_mode(0)  {
    }
  standby_modeRequest_(const ContainerAllocator& _alloc)
    : standby_mode(0)  {
  (void)_alloc;
    }



   typedef int8_t _standby_mode_type;
  _standby_mode_type standby_mode;





  typedef boost::shared_ptr< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct standby_modeRequest_

typedef ::lslidar_ls_driver::standby_modeRequest_<std::allocator<void> > standby_modeRequest;

typedef boost::shared_ptr< ::lslidar_ls_driver::standby_modeRequest > standby_modeRequestPtr;
typedef boost::shared_ptr< ::lslidar_ls_driver::standby_modeRequest const> standby_modeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.standby_mode == rhs.standby_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator1> & lhs, const ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_ls_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "422a2076f0ec4f22c47bea3a3afdb473";
  }

  static const char* value(const ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x422a2076f0ec4f22ULL;
  static const uint64_t static_value2 = 0xc47bea3a3afdb473ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_ls_driver/standby_modeRequest";
  }

  static const char* value(const ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 standby_mode\n"
;
  }

  static const char* value(const ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.standby_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct standby_modeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_ls_driver::standby_modeRequest_<ContainerAllocator>& v)
  {
    s << indent << "standby_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.standby_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_LS_DRIVER_MESSAGE_STANDBY_MODEREQUEST_H
