// Generated by gencpp from file lslidar_ls_driver/standby_mode.msg
// DO NOT EDIT!


#ifndef LSLIDAR_LS_DRIVER_MESSAGE_STANDBY_MODE_H
#define LSLIDAR_LS_DRIVER_MESSAGE_STANDBY_MODE_H

#include <ros/service_traits.h>


#include <lslidar_ls_driver/standby_modeRequest.h>
#include <lslidar_ls_driver/standby_modeResponse.h>


namespace lslidar_ls_driver
{

struct standby_mode
{

typedef standby_modeRequest Request;
typedef standby_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct standby_mode
} // namespace lslidar_ls_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lslidar_ls_driver::standby_mode > {
  static const char* value()
  {
    return "1624e82515d941105debf01f9e74621c";
  }

  static const char* value(const ::lslidar_ls_driver::standby_mode&) { return value(); }
};

template<>
struct DataType< ::lslidar_ls_driver::standby_mode > {
  static const char* value()
  {
    return "lslidar_ls_driver/standby_mode";
  }

  static const char* value(const ::lslidar_ls_driver::standby_mode&) { return value(); }
};


// service_traits::MD5Sum< ::lslidar_ls_driver::standby_modeRequest> should match
// service_traits::MD5Sum< ::lslidar_ls_driver::standby_mode >
template<>
struct MD5Sum< ::lslidar_ls_driver::standby_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_ls_driver::standby_mode >::value();
  }
  static const char* value(const ::lslidar_ls_driver::standby_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_ls_driver::standby_modeRequest> should match
// service_traits::DataType< ::lslidar_ls_driver::standby_mode >
template<>
struct DataType< ::lslidar_ls_driver::standby_modeRequest>
{
  static const char* value()
  {
    return DataType< ::lslidar_ls_driver::standby_mode >::value();
  }
  static const char* value(const ::lslidar_ls_driver::standby_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lslidar_ls_driver::standby_modeResponse> should match
// service_traits::MD5Sum< ::lslidar_ls_driver::standby_mode >
template<>
struct MD5Sum< ::lslidar_ls_driver::standby_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_ls_driver::standby_mode >::value();
  }
  static const char* value(const ::lslidar_ls_driver::standby_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_ls_driver::standby_modeResponse> should match
// service_traits::DataType< ::lslidar_ls_driver::standby_mode >
template<>
struct DataType< ::lslidar_ls_driver::standby_modeResponse>
{
  static const char* value()
  {
    return DataType< ::lslidar_ls_driver::standby_mode >::value();
  }
  static const char* value(const ::lslidar_ls_driver::standby_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LSLIDAR_LS_DRIVER_MESSAGE_STANDBY_MODE_H
