// Generated by gencpp from file serial_msgs/air_pressure.msg
// DO NOT EDIT!


#ifndef SERIAL_MSGS_MESSAGE_AIR_PRESSURE_H
#define SERIAL_MSGS_MESSAGE_AIR_PRESSURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace serial_msgs
{
template <class ContainerAllocator>
struct air_pressure_
{
  typedef air_pressure_<ContainerAllocator> Type;

  air_pressure_()
    : header()
    , pressure(0.0)
    , altitude_false(0.0)
    , altitude_true(0.0)
    , velocity(0.0)  {
    }
  air_pressure_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pressure(0.0)
    , altitude_false(0.0)
    , altitude_true(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _pressure_type;
  _pressure_type pressure;

   typedef float _altitude_false_type;
  _altitude_false_type altitude_false;

   typedef float _altitude_true_type;
  _altitude_true_type altitude_true;

   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::serial_msgs::air_pressure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_msgs::air_pressure_<ContainerAllocator> const> ConstPtr;

}; // struct air_pressure_

typedef ::serial_msgs::air_pressure_<std::allocator<void> > air_pressure;

typedef boost::shared_ptr< ::serial_msgs::air_pressure > air_pressurePtr;
typedef boost::shared_ptr< ::serial_msgs::air_pressure const> air_pressureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_msgs::air_pressure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_msgs::air_pressure_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_msgs::air_pressure_<ContainerAllocator1> & lhs, const ::serial_msgs::air_pressure_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pressure == rhs.pressure &&
    lhs.altitude_false == rhs.altitude_false &&
    lhs.altitude_true == rhs.altitude_true &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_msgs::air_pressure_<ContainerAllocator1> & lhs, const ::serial_msgs::air_pressure_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_msgs::air_pressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_msgs::air_pressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_msgs::air_pressure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_msgs::air_pressure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_msgs::air_pressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_msgs::air_pressure_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_msgs::air_pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd17d505d4d8356e7134f196e7c31915";
  }

  static const char* value(const ::serial_msgs::air_pressure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd17d505d4d8356eULL;
  static const uint64_t static_value2 = 0x7134f196e7c31915ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_msgs::air_pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_msgs/air_pressure";
  }

  static const char* value(const ::serial_msgs::air_pressure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_msgs::air_pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 pressure\n"
"float32 altitude_false\n"
"float32 altitude_true\n"
"float32 velocity\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::serial_msgs::air_pressure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_msgs::air_pressure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pressure);
      stream.next(m.altitude_false);
      stream.next(m.altitude_true);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct air_pressure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_msgs::air_pressure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_msgs::air_pressure_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
    s << indent << "altitude_false: ";
    Printer<float>::stream(s, indent + "  ", v.altitude_false);
    s << indent << "altitude_true: ";
    Printer<float>::stream(s, indent + "  ", v.altitude_true);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_MSGS_MESSAGE_AIR_PRESSURE_H
